---
apiVersion: v1
kind: Service
metadata:
  name: nfssvc
  namespace: yunwei
spec:
  ports:
    - name: web
      port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: nfssvc
  sessionAffinity: ClientIP

# Ingress
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nfssvc
  namespace: yunwei
  # annotations:
  #traefik.ingress.kubernetes.io/frontend-entry-points: http,https
  # traefik.ingress.kubernetes.io/redirect-entry-point: https
spec:
  rules:
    # curl nfssvc.newops.haodai.net/api/
    - host: nfssvc.newops.haodai.net
      http:
        paths:
          - path: /
            backend:
              serviceName: nfssvc
              servicePort: web
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: nfssvc
  namespace: yunwei
  labels:
    app: nfssvc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nfssvc
  template:
    metadata:
      labels:
        app: nfssvc
    spec:
      containers:
        - name: nfssvc
          image: harbor.haodai.net/ops/nfssvc:v1
          imagePullPolicy: Always
          args:
            - /app/nfssvc
            - -path
            - /data/nfslist/exports
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: data
              mountPath: /data/nfslist
              # subPath: exports
      volumes:
        - name: data
          nfs:
            path: /data/nfslist
            server: 172.31.83.26
      nodeSelector:
        #kubernetes.io/hostname: 172.31.90.208
        # func: monitor
        env: yunwei
